basePath: /
definitions:
  domain.Category:
    properties:
      description:
        type: string
      id:
        type: integer
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is a sample swagger for Fiber
  title: Fiber Example API
  version: "1.0"
paths:
  /categories:
    post:
      consumes:
      - application/json
      description: Cria uma nova categoria.
      parameters:
      - description: Categoria a ser criada
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/domain.Category'
      produces:
      - application/json
      responses:
        "201":
          description: Categoria criada com sucesso
      summary: Criar uma categoria
      tags:
      - categories
swagger: "2.0"
