version: "3.9"

services:
  db:
    network_mode: "host"
    image: mysql:latest
    container_name: tica-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: tica
      MYSQL_USER: tica
      MYSQL_PASSWORD: senha123
    volumes:
      - /data:/var/lib/mysql
    ports:
      - "3306:3306"