version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: tica-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: tica
      MYSQL_USER: tica
      MYSQL_PASSWORD: senha123
    volumes:
      - /data:/var/lib/mysql
    ports:
      - "3306:3306"

  api:
    build: .
    container_name: tica-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["sh", "-c", "sleep 5 && make migrate-dev-up && make seed-database && ./main"] 
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=tica
      - MYSQL_USER=tica
      - MYSQL_PASSWORD=senha123
      - MYSQL_TLS=false